"""Compatibility imports for The Weather Company client package."""

from __future__ import annotations

from .twc_weather_client import (
    TWCAuthError,
    TWCClient,
    TWCError,
    TWCNoDataError,
    TWCPermissionError,
    TWCRequestError,
)
from .twc_weather_client.client import (
    AIR_QUALITY_PATH,
    ALERT_HEADLINES_PATH,
    BASE_URL,
    CURRENT_PATH,
    DAILY_FORECAST_PATH,
    DAILY_FORECAST_PATH_PREFIX,
    DEFAULT_AIR_QUALITY_SCALE,
    DEFAULT_DAILY_FORECAST_DURATION,
    DEFAULT_HOURLY_FORECAST_DURATION,
    DEFAULT_POLLEN_FORECAST_DURATION,
    HOURLY_FORECAST_PATH,
    HOURLY_FORECAST_PATH_PREFIX,
    POLLEN_FORECAST_PATH,
    POLLEN_FORECAST_PATH_PREFIX,
    POLLEN_OBSERVATION_PATH,
    TROPICAL_CURRENT_POSITION_PATH,
)

__all__ = [
    "AIR_QUALITY_PATH",
    "ALERT_HEADLINES_PATH",
    "BASE_URL",
    "CURRENT_PATH",
    "DAILY_FORECAST_PATH",
    "DAILY_FORECAST_PATH_PREFIX",
    "DEFAULT_AIR_QUALITY_SCALE",
    "DEFAULT_DAILY_FORECAST_DURATION",
    "DEFAULT_HOURLY_FORECAST_DURATION",
    "DEFAULT_POLLEN_FORECAST_DURATION",
    "HOURLY_FORECAST_PATH",
    "HOURLY_FORECAST_PATH_PREFIX",
    "POLLEN_FORECAST_PATH",
    "POLLEN_FORECAST_PATH_PREFIX",
    "POLLEN_OBSERVATION_PATH",
    "TROPICAL_CURRENT_POSITION_PATH",
    "TWCAuthError",
    "TWCClient",
    "TWCError",
    "TWCNoDataError",
    "TWCPermissionError",
    "TWCRequestError",
]
